[package]
name = "sequesteredone/sworduh"
version = "0.3.5-beta"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"
exclude = [
    "assets",
    "default.project.json",
    "moonwave.toml",
    "rokit.toml",
    "sourcemap.json",
    "Packages",
    "DevPackages",
    "node_modules",
    "globalTypes.d.luau",
    "Sworduh.rbxlx",
    "tests-d",
    "selene.toml",
    "pnpm-lock.yaml",
    "package.json",
    "tsconfig.json",
    "types"
]

[dev-dependencies]
jest = "jsdotlua/jest@3.10.0"

[dependencies]
promise = "evaera/promise@4.0.0"
